In [2]:
import pandas as pd
# notice the need to danda import to have accessor df
import danda # noqa: F401  # registers the pandas accessor
from danda.report_renderer import ReportRenderer

renderer = ReportRenderer()

In [3]:
df = pd.DataFrame({
    # Boolean-like strings and integers
    "IsActive": ["True", "false", "1", "0", None],
    "Verified": [1, 0, 1, 0, None],

    # Datetime-like strings
    "OrderDate": [
        "2024-01-01",
        "2024-02-15",
        "2024-03-20",
        None,
        "2024-04-10",
    ],

    # Numeric strings
    "Age": ["25", "30", "35", None, "40"],
    "Salary": ["50000.5", "62000", "71000.25", "80000", None],

    # Low-cardinality text
    "Department": ["HR", "IT", "HR", "IT", "HR"],
    "Region": ["East", "West", "East", "West", "East"],

    # High-cardinality text (should remain object/string)
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
})

print(df.dtypes)
df

IsActive          str
Verified      float64
OrderDate         str
Age               str
Salary            str
Department        str
Region            str
Name              str
dtype: object

  IsActive  Verified   OrderDate  Age    Salary Department Region     Name
0     True       1.0  2024-01-01   25   50000.5         HR   East    Alice
1    false       0.0  2024-02-15   30     62000         IT   West      Bob
2        1       1.0  2024-03-20   35  71000.25         HR   East  Charlie
3        0       0.0         NaN  NaN     80000         IT   West    David
4      NaN       NaN  2024-04-10   40       NaN         HR   East      Eve

In [7]:
optimized_df = df.dg.optimize()

print(optimized_df.dtypes)
optimized_df

IsActive             boolean
Verified             float64
OrderDate     datetime64[us]
Age                  float64
Salary               float64
Department               str
Region                   str
Name                     str
dtype: object

   IsActive  Verified  OrderDate   Age    Salary Department Region     Name
0      True       1.0 2024-01-01  25.0  50000.50         HR   East    Alice
1     False       0.0 2024-02-15  30.0  62000.00         IT   West      Bob
2      True       1.0 2024-03-20  35.0  71000.25         HR   East  Charlie
3     False       0.0        NaT   NaN  80000.00         IT   West    David
4      <NA>       NaN 2024-04-10  40.0       NaN         HR   East      Eve

## Improve the configuration
this is a small data, and thus the optimizer could not classify Department and Region as category type. we can help it to do that by changing `category_threshold` whch has a default of 10%

In [8]:
df.dg.config.types.category_threshold = .4

In [9]:
optimized_df = df.dg.optimize()

print(optimized_df.dtypes)
optimized_df

IsActive             boolean
Verified             float64
OrderDate     datetime64[us]
Age                  float64
Salary               float64
Department          category
Region              category
Name                     str
dtype: object

   IsActive  Verified  OrderDate   Age    Salary Department Region     Name
0      True       1.0 2024-01-01  25.0  50000.50         HR   East    Alice
1     False       0.0 2024-02-15  30.0  62000.00         IT   West      Bob
2      True       1.0 2024-03-20  35.0  71000.25         HR   East  Charlie
3     False       0.0        NaT   NaN  80000.00         IT   West    David
4      <NA>       NaN 2024-04-10  40.0       NaN         HR   East      Eve