In [1]:
import pandas as pd
from pprint import pprint
import danda  # noqa: F401  # registers the pandas accessor

In [2]:
df = pd.DataFrame({
    "approved": [
        "Yes",
        "No",
        "Yes",
        "No",
        None,
        "Yes",
    ],
    "status": [
        "OK",
        "N/A",
        "Unknown",
        "-",
        "OK",
        None,
    ],
    "age": [
        25,
        None,
        31,
        None,
        45,
        None,
    ],
    "salary": [
        None,
        None,
        50000,
        None,
        None,
        60000,
    ],
    "email": [
        "alice@example.com",
        "bob@example.com",
        None,
        "david@example.com",
        "eve@example.com",
        "frank@example.com",
    ],
})

result = df.dg.analyze()
pprint(result.dg.report)
df

{'analyze': {'analysis': {'MissingValuesReportPlugin': 'Missing values '
                                                       'detected:\n'
                                                       '- salary: 4 (66.7%)\n'
                                                       '- age: 3 (50.0%)\n'
                                                       '- approved: 1 (16.7%)\n'
                                                       '- email: 1 (16.7%)\n'
                                                       '- status: 1 (16.7%)',
                          'MissingValuesSummaryPlugin': 'Missing Value '
                                                        'Summary\n'
                                                        'Rows: 6\n'
                                                        'Columns: 5\n'
                                                        '\n'
                                                        'Missing cells: 10 '
                                                        '(33.3%)\n'
                                                        'Columns with missing: '
                                                        '5\n'
                                                        'Rows with missing: 6\n'
                                                        'Complete rows: 0 '
                                                        '(0.0%)',
                          'PotentialBooleanTypePlugin': 'Columns that may '
                                                        'represent boolean '
                                                        'values:\n'
                                                        " - approved: ['yes', "
                                                        "'no']\n"
                                                        ' - salary: '
                                                        '[np.float64(50000.0), '
                                                        'np.float64(60000.0)]',
                          'PotentialMissingValuesPlugin': 'Potential missing '
                                                          'values detected:\n'
                                                          '- status: n/a (1), '
                                                          '- (1)',
                          'SuspiciousMissingValuesPlugin': 'Suspicious missing '
                                                           'value indicators '
                                                           'detected:\n'
                                                           '- status: UNKNOWN '
                                                           '(1)'},
             'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(484),
                                                        'before_bytes': np.int64(484),
                                                        'saved_bytes': np.int64(0),
                                                        'saved_percent': np.float64(0.0)},
                                       'plugin_names': ['MissingValuesSummaryPlugin',
                                                        'MissingValuesReportPlugin',
                                                        'PotentialMissingValuesPlugin',
                                                        'SuspiciousMissingValuesPlugin',
                                                        'PotentialBooleanTypePlugin'],
                                       'plugins_count': 5}}}}

  approved   status   age   salary              email
0      Yes       OK  25.0      NaN  alice@example.com
1       No      N/A   NaN      NaN    bob@example.com
2      Yes  Unknown  31.0  50000.0                NaN
3       No        -   NaN      NaN  david@example.com
4      NaN       OK  45.0      NaN    eve@example.com
5      Yes      NaN   NaN  60000.0  frank@example.com

In [4]:
df = pd.DataFrame({
    "bool_text": [
        "True",
        "False",
        "TRUE",
        "FALSE",
        "True",
    ],
    "approved": [
        "Yes",
        "No",
        "YES",
        "NO",
        "  yes",
    ],
    "status": [
        "OK",
        "N/A",
        "Unknown",
        "-",
        "OK",
    ],
    "notes": [
        "Some text",
        "Another note",
        "More text",
        "Last note",
        "Done",
    ],
    "number": [
        1,
        2,
        3,
        4,
        5,
    ],
})
df

  bool_text approved   status         notes  number
0      True      Yes       OK     Some text       1
1     False       No      N/A  Another note       2
2      TRUE      YES  Unknown     More text       3
3     FALSE       NO        -     Last note       4
4      True      yes       OK          Done       5

In [5]:
from pprint import pprint

result = df.dg.analyze()
pprint(result.dg.report)

{'analyze': {'analysis': {'MissingValuesReportPlugin': 'No missing values '
                                                       'detected.',
                          'PotentialBooleanTypePlugin': 'Columns that may '
                                                        'represent boolean '
                                                        'values:\n'
                                                        " - approved: ['yes', "
                                                        "'no']",
                          'PotentialMissingValuesPlugin': 'Potential missing '
                                                          'values detected:\n'
                                                          '- status: n/a (1), '
                                                          '- (1)',
                          'SuspiciousMissingValuesPlugin': 'Suspicious missing '
                                                           'value indicators '
                                                           'detected:\n'
                                                           '- status: UNKNOWN '
                                                           '(1)'},
             'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(427),
                                                        'before_bytes': np.int64(427),
                                                        'saved_bytes': np.int64(0),
                                                        'saved_percent': np.float64(0.0)},
                                       'plugin_names': ['PotentialBooleanTypePlugin',
                                                        'PotentialMissingValuesPlugin',
                                                        'MissingValuesReportPlugin',
                                                        'SuspiciousMissingValuesPlugin'],
                                       'plugins_count': 4}}}}

In [6]:
df = pd.DataFrame({
    "approved": [
        "Yes",
        "No",
        "Yes",
        "No",
    ],
    "status": [
        "OK",
        "N/A",
        "Unknown",
        "-",
    ],
    "name": [
        "Alice",
        "Bob",
        "Charlie",
        "David",
    ],
})

In [7]:
from pprint import pprint

result = df.dg.analyze()
pprint(result.dg.report)

{'analyze': {'analysis': {'MissingValuesReportPlugin': 'No missing values '
                                                       'detected.',
                          'PotentialBooleanTypePlugin': 'Columns that may '
                                                        'represent boolean '
                                                        'values:\n'
                                                        " - approved: ['yes', "
                                                        "'no']",
                          'PotentialMissingValuesPlugin': 'Potential missing '
                                                          'values detected:\n'
                                                          '- status: n/a (1), '
                                                          '- (1)',
                          'SuspiciousMissingValuesPlugin': 'Suspicious missing '
                                                           'value indicators '
                                                           'detected:\n'
                                                           '- status: UNKNOWN '
                                                           '(1)'},
             'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(271),
                                                        'before_bytes': np.int64(271),
                                                        'saved_bytes': np.int64(0),
                                                        'saved_percent': np.float64(0.0)},
                                       'plugin_names': ['PotentialBooleanTypePlugin',
                                                        'PotentialMissingValuesPlugin',
                                                        'MissingValuesReportPlugin',
                                                        'SuspiciousMissingValuesPlugin'],
                                       'plugins_count': 4}}}}

In [8]:
df = pd.DataFrame({
    "approved": [
        "Yes",
        "No",
        "yes",
        "NO",
        None,
        "Yes",
    ],

    "status": [
        "N/A",
        " n/a ",
        "?",
        "Active",
        None,
        "OK",
    ],

    "age": [
        25,
        999,
        -999,
        None,
        30,
        40,
    ],

    "salary": [
        50000,
        None,
        60000,
        None,
        None,
        None,
    ],

    "email": [
        "a@example.com",
        None,
        "b@example.com",
        "c@example.com",
        None,
        "d@example.com",
    ],
})
df

  approved  status    age   salary          email
0      Yes     N/A   25.0  50000.0  a@example.com
1       No    n/a   999.0      NaN            NaN
2      yes       ? -999.0  60000.0  b@example.com
3       NO  Active    NaN      NaN  c@example.com
4      NaN     NaN   30.0      NaN            NaN
5      Yes      OK   40.0      NaN  d@example.com

In [9]:
result = df.dg.analyze()
pprint(result.dg.report)

{'analyze': {'analysis': {'MissingValuesReportPlugin': 'Missing values '
                                                       'detected:\n'
                                                       '- salary: 4 (66.7%)\n'
                                                       '- email: 2 (33.3%)\n'
                                                       '- age: 1 (16.7%)\n'
                                                       '- approved: 1 (16.7%)\n'
                                                       '- status: 1 (16.7%)',
                          'PotentialBooleanTypePlugin': 'Columns that may '
                                                        'represent boolean '
                                                        'values:\n'
                                                        " - approved: ['yes', "
                                                        "'no']\n"
                                                        ' - salary: '
                                                        '[np.float64(50000.0), '
                                                        'np.float64(60000.0)]',
                          'PotentialMissingValuesPlugin': 'Potential missing '
                                                          'values detected:\n'
                                                          '- status: n/a (2), '
                                                          '? (1)',
                          'SuspiciousMissingValuesPlugin': 'Suspicious missing '
                                                           'value indicators '
                                                           'detected:\n'
                                                           '- age: 999 (1), '
                                                           '-999 (1)'},
             'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(457),
                                                        'before_bytes': np.int64(457),
                                                        'saved_bytes': np.int64(0),
                                                        'saved_percent': np.float64(0.0)},
                                       'plugin_names': ['PotentialBooleanTypePlugin',
                                                        'PotentialMissingValuesPlugin',
                                                        'MissingValuesReportPlugin',
                                                        'SuspiciousMissingValuesPlugin'],
                                       'plugins_count': 4}}}}