In [1]:
import pandas as pd
import danda  # noqa: F401  # registers the pandas accessor

df = pd.DataFrame({
    "A": [1, 1, None, None, None],
    "B": [2, None, None, None, None],
    "C": [3, None, None, None, None],
    "D": [4, None, None, None, None],
    "E": [5, 5, None, None, None],
})

df

     A    B    C    D    E
0  1.0  2.0  3.0  4.0  5.0
1  1.0  NaN  NaN  NaN  5.0
2  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN

In [2]:
df.dg.config.cleaning.sparse_rows_enabled = True
df.dg.config.cleaning.sparse_rows_threshold = 0.8

In [3]:
from pprint import pprint

result = df.dg.clean()
pprint(result.dg.report)
result

{'clean': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(212),
                                                      'before_bytes': np.int64(332),
                                                      'saved_bytes': np.int64(120),
                                                      'saved_percent': np.float64(36.144578313253014)},
                                     'plugin_names': ['EmptySpacesPlugin',
                                                      'NormalizeMissingValuesPlugin',
                                                      'SparseColumnsPlugin',
                                                      'SparseRowsPlugin',
                                                      'EmptyRowsPlugin',
                                                      'EmptyColumnsPlugin',
                                                      'DropDuplicates'],
                                     'plugins_count': 7}},
           'clean': {'DropDuplicates': 'Number of deleted rows: 0',
                     'EmptyColumnsPlugin': 'Number of deleted columns: 0',
                     'EmptyRowsPlugin': 'Number of deleted rows: 0',
                     'EmptySpacesPlugin': 'No leading or trailing whitespace '
                                          'found.',
                     'NormalizeMissingValuesPlugin': 'No missing values were '
                                                     'normalized.',
                     'SparseRowsPlugin': 'Removed 3 sparse rows.'}}}

     A    B    C    D    E
0  1.0  2.0  3.0  4.0  5.0
1  1.0  NaN  NaN  NaN  5.0