In [1]:
import pandas as pd
import danda  # noqa: F401  # registers the pandas accessor

In [2]:
df = pd.DataFrame({
    # Numeric
    "age": [20, None, 30, None, 40],

    # Boolean (converted by optimize())
    "approved": ["TRUE", None, "FALSE", "true", None],

    # Category (low cardinality)
    "department": ["IT", "HR", None, "IT", "HR"],

    # Text (high cardinality)
    "city": [
        "Berlin",
        None,
        "Paris",
        "London",
        "Madrid",
    ],

    # Datetime
    "hire_date": [
        "2024-01-01",
        None,
        "2024-01-03",
        None,
        "2024-01-05",
    ],
})
print(df.info())
df

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         3 non-null      float64
 1   approved    3 non-null      str
 2   department  4 non-null      str
 3   city        4 non-null      str
 4   hire_date   3 non-null      str
dtypes: float64(1), str(4)
memory usage: 410.0 bytes
None

    age approved department    city   hire_date
0  20.0     TRUE         IT  Berlin  2024-01-01
1   NaN      NaN         HR     NaN         NaN
2  30.0    FALSE        NaN   Paris  2024-01-03
3   NaN     true         IT  London         NaN
4  40.0      NaN         HR  Madrid  2024-01-05

In [5]:
from pprint import pprint
df.dg.config.types.category_threshold =.5
result = (
    df
    .dg.clean()
    .dg.optimize()
)
pprint(result.dg.report)
print(result.info())
result

{'clean': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(410),
                                                      'before_bytes': np.int64(410),
                                                      'saved_bytes': np.int64(0),
                                                      'saved_percent': np.float64(0.0)},
                                     'plugin_names': ['EmptySpacesPlugin',
                                                      'NormalizeMissingValuesPlugin',
                                                      'SparseColumnsPlugin',
                                                      'SparseRowsPlugin',
                                                      'EmptyRowsPlugin',
                                                      'EmptyColumnsPlugin',
                                                      'DropDuplicates'],
                                     'plugins_count': 7}},
           'clean': {'DropDuplicates': 'Number of deleted rows: 0',
                     'EmptyColumnsPlugin': 'Number of deleted columns: 0',
                     'EmptyRowsPlugin': 'Number of deleted rows: 0',
                     'EmptySpacesPlugin': 'No leading or trailing whitespace '
                                          'found.',
                     'NormalizeMissingValuesPlugin': 'No missing values were '
                                                     'normalized.'}},
 'optimize': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(312),
                                                         'before_bytes': np.int64(410),
                                                         'saved_bytes': np.int64(98),
                                                         'saved_percent': np.float64(23.902439024390244)},
                                        'plugin_names': ['BooleanTypePlugin',
                                                         'DateTimeTypePlugin',
                                                         'NumericTypePlugin',
                                                         'CategoryTypePlugin'],
                                        'plugins_count': 4}},
              'types': {'BooleanTypePlugin': 'convert these columns to boolean '
                                             'approved',
                        'CategoryTypePlugin': 'No category columns detected.',
                        'DateTimeTypePlugin': 'Converted the following columns '
                                              'to datetime: hire_date',
                        'NumericTypePlugin': 'No numeric columns detected.'}}}
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         3 non-null      float64
 1   approved    3 non-null      boolean
 2   department  4 non-null      category
 3   city        4 non-null      str
 4   hire_date   3 non-null      datetime64[us]
dtypes: boolean(1), category(1), datetime64[us](1), float64(1), str(1)
memory usage: 312.0 bytes
None

    age  approved department    city  hire_date
0  20.0      True         IT  Berlin 2024-01-01
1   NaN      <NA>         HR     NaN        NaT
2  30.0     False        NaN   Paris 2024-01-03
3   NaN      True         IT  London        NaT
4  40.0      <NA>         HR  Madrid 2024-01-05

In [9]:
result.dg.config.imputation.enabled = True
result1 = result.dg.impute()
result1

    age  approved department    city  hire_date
0  20.0      True         IT  Berlin 2024-01-01
1  30.0      True         HR  Berlin 2024-01-01
2  30.0     False         HR   Paris 2024-01-03
3  30.0      True         IT  London 2024-01-03
4  40.0      True         HR  Madrid 2024-01-05

In [7]:
result1

    age  approved department    city  hire_date
0  20.0      True         IT  Berlin 2024-01-01
1   NaN      <NA>         HR     NaN        NaT
2  30.0     False        NaN   Paris 2024-01-03
3   NaN      True         IT  London        NaT
4  40.0      <NA>         HR  Madrid 2024-01-05