In [1]:
import pandas as pd
import danda # noqa: F401  # registers the pandas accessor
from danda.report_renderer import ReportRenderer

In [5]:
import pandas as pd

df = pd.DataFrame({
    "age": [
        24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        25, 26, 27, 28,
        45,   # borderline
        60,   # borderline
        90,   # high but may/may not be flagged
        120,  # definite outlier
        -20,  # low but may not be flagged
        -50   # definite low outlier
    ],

    "salary": [
        48000, 49500, 50000, 50500, 51000, 51500, 52000, 52500, 53000, 53500,
        49000, 50000, 51000, 52000, 53000, 54000, 55000, 56000, 57000, 58000,
        49500, 50500, 51500, 52500,
        65000,    # borderline
        90000,    # high but probably not
        120000,   # possible outlier
        500000,   # definite outlier
        1000,     # low but may not
        -100000   # definite low outlier
    ],

    "height": [
        168, 169, 170, 171, 172, 173, 174, 170, 171, 172,
        169, 170, 171, 172, 173, 174, 175, 171, 172, 173,
        170, 171, 172, 173,
        180,   # borderline
        190,   # high but probably not
        205,   # possible outlier
        250,   # definite outlier
        80,    # definite outlier
        40     # definite outlier
    ],

    "score": [
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        87, 88, 89, 90,
        96,    # borderline
        98,    # high but probably not
        100,   # high
        120,   # definite outlier
        0,     # definite outlier
        -20    # definite outlier
    ],

    "city": [
        "London", "Paris", "Rome", "Berlin", "Madrid",
        "Lisbon", "Vienna", "Prague", "Warsaw", "Dublin",
        "Oslo", "Stockholm", "Helsinki", "Copenhagen", "Brussels",
        "Amsterdam", "Zurich", "Geneva", "Athens", "Budapest",
        "Sofia", "Zagreb", "Belgrade", "Ljubljana",
        "Sarajevo", "Skopje", "Tallinn",
        "Tokyo", "Sydney", "New York"
    ]
})

df

    age  salary  height  score        city
0    24   48000     168     85      London
1    25   49500     169     86       Paris
2    26   50000     170     87        Rome
3    27   50500     171     88      Berlin
4    28   51000     172     89      Madrid
5    29   51500     173     90      Lisbon
6    30   52000     174     91      Vienna
7    31   52500     170     92      Prague
8    32   53000     171     93      Warsaw
9    33   53500     172     94      Dublin
10   24   49000     169     86        Oslo
11   25   50000     170     87   Stockholm
12   26   51000     171     88    Helsinki
13   27   52000     172     89  Copenhagen
14   28   53000     173     90    Brussels
15   29   54000     174     91   Amsterdam
16   30   55000     175     92      Zurich
17   31   56000     171     93      Geneva
18   32   57000     172     94      Athens
19   33   58000     173     95    Budapest
20   25   49500     170     87       Sofia
21   26   50500     171     88      Zagreb
22   27   51500     172     89    Belgrade
23   28   52500     173     90   Ljubljana
24   45   65000     180     96    Sarajevo
25   60   90000     190     98      Skopje
26   90  120000     205    100     Tallinn
27  120  500000     250    120       Tokyo
28  -20    1000      80      0      Sydney
29  -50 -100000      40    -20    New York

In [6]:
report = df.dg.analyze().dg.report

In [7]:
renderer = ReportRenderer()
print(renderer.render(report))

============
Danda Report
============

Analyze
-------

ColumnSummary
    Column Summary:

    age
    Type: int64
    Missing: 0 (0%)
    Unique: 16

    salary
    Type: int64
    Missing: 0 (0%)
    Unique: 22

    height
    Type: int64
    Missing: 0 (0%)
    Unique: 14

    score
    Type: int64
    Missing: 0 (0%)
    Unique: 17

    city
    Type: str
    Missing: 0 (0%)
    Unique: 30

MissingValuesSummaryPlugin
    Missing Value Summary
    Rows: 30
    Columns: 5

    Missing cells: 0 (0.0%)
    Columns with missing: 0
    Rows with missing: 0
    Complete rows: 30 (100.0%)

OutlierReport
    Outliers detected:

    Legend:
    <  Bound lies below observed values
    >  Bound lies above observed values
    =  Values within normal bounds
    -  Outlier region
    |  Outlier threshold

    score
    Method: MODIFIED-ZSCORE (×3.0)
    Outliers: 2 of 30 (6.67%)
    Outlier Interval: -20 to 0

    Bounds:
    Lower: 9.82
    Upper: 170.18

    -20                                            120
    ----------|======================================>
             LB
    Examples:
    - Row 28: 0
    - Row 29: -20

    Note:
    A relatively large proportion of values were classified as outliers.
    This may indicate a skewed distribution rather than data quality issues.

    age
    Method: MODIFIED-ZSCORE (×3.0)
    Outliers: 1 of 30 (3.33%)
    Outlier Interval: 120 to 120

    Bounds:
    Lower: -54.58
    Upper: 110.58

    -50                                            120
    <=============================================|---
                                                 UB
    Examples:
    - Row 27: 120

    height
    Method: MODIFIED-ZSCORE (×3.0)
    Outliers: 1 of 30 (3.33%)
    Outlier Interval: 40 to 40

    Bounds:
    Lower: 70.5
    Upper: 273.5

    40                                             250
    -------|=========================================>
          LB
    Examples:
    - Row 29: 40

    salary
    Method: MODIFIED-ZSCORE (×3.0)
    Outliers: 1 of 30 (3.33%)
    Outlier Interval: 500,000 to 500,000

    Bounds:
    Lower: -214,189.11
    Upper: 318,189.11

    -100000                                     500000
    <=================================|---------------
                                     UB
    Examples:
    - Row 27: 500000

Execution
---------
Plugins executed : 9
Plugin names     : ColumnSummary, MissingValuesSummaryPlugin, MissingValuesReportPlugin, PotentialMissingValuesPlugin, SuspiciousMissingValuesPlugin, SparseRowsReportPlugin, PotentialBooleanTypePlugin, ConstantColumns, OutlierReport

In [8]:
# age[27] = nan
noout = df.dg.action.handle_outliers(
    columns=["age"],
    strategy="nan",
)
noout

     age  salary  height  score        city
0   24.0   48000     168     85      London
1   25.0   49500     169     86       Paris
2   26.0   50000     170     87        Rome
3   27.0   50500     171     88      Berlin
4   28.0   51000     172     89      Madrid
5   29.0   51500     173     90      Lisbon
6   30.0   52000     174     91      Vienna
7   31.0   52500     170     92      Prague
8   32.0   53000     171     93      Warsaw
9   33.0   53500     172     94      Dublin
10  24.0   49000     169     86        Oslo
11  25.0   50000     170     87   Stockholm
12  26.0   51000     171     88    Helsinki
13  27.0   52000     172     89  Copenhagen
14  28.0   53000     173     90    Brussels
15  29.0   54000     174     91   Amsterdam
16  30.0   55000     175     92      Zurich
17  31.0   56000     171     93      Geneva
18  32.0   57000     172     94      Athens
19  33.0   58000     173     95    Budapest
20  25.0   49500     170     87       Sofia
21  26.0   50500     171     88      Zagreb
22  27.0   51500     172     89    Belgrade
23  28.0   52500     173     90   Ljubljana
24  45.0   65000     180     96    Sarajevo
25  60.0   90000     190     98      Skopje
26  90.0  120000     205    100     Tallinn
27   NaN  500000     250    120       Tokyo
28 -20.0    1000      80      0      Sydney
29 -50.0 -100000      40    -20    New York

In [9]:
# before clipping age[27] has a value of 120 age uper is 110.xx
# age[27] = 110.xx
noout = df.dg.action.handle_outliers(
    columns=["age"],
    strategy="clip",
)
noout

           age  salary  height  score        city
0    24.000000   48000     168     85      London
1    25.000000   49500     169     86       Paris
2    26.000000   50000     170     87        Rome
3    27.000000   50500     171     88      Berlin
4    28.000000   51000     172     89      Madrid
5    29.000000   51500     173     90      Lisbon
6    30.000000   52000     174     91      Vienna
7    31.000000   52500     170     92      Prague
8    32.000000   53000     171     93      Warsaw
9    33.000000   53500     172     94      Dublin
10   24.000000   49000     169     86        Oslo
11   25.000000   50000     170     87   Stockholm
12   26.000000   51000     171     88    Helsinki
13   27.000000   52000     172     89  Copenhagen
14   28.000000   53000     173     90    Brussels
15   29.000000   54000     174     91   Amsterdam
16   30.000000   55000     175     92      Zurich
17   31.000000   56000     171     93      Geneva
18   32.000000   57000     172     94      Athens
19   33.000000   58000     173     95    Budapest
20   25.000000   49500     170     87       Sofia
21   26.000000   50500     171     88      Zagreb
22   27.000000   51500     172     89    Belgrade
23   28.000000   52500     173     90   Ljubljana
24   45.000000   65000     180     96    Sarajevo
25   60.000000   90000     190     98      Skopje
26   90.000000  120000     205    100     Tallinn
27  110.580932  500000     250    120       Tokyo
28  -20.000000    1000      80      0      Sydney
29  -50.000000 -100000      40    -20    New York